version: "3"
services:
  mongodb:
    container_name: mongo
    image: mongo
    restart: unless-stopped
    volumes:
      - ./db:/data/db
    ports:
      - $DOCKER_MONGODB_PORT:$MONGODB_PORT  
  watchcat:
    container_name: watchcat
    image: mizosoft/watchcat
    restart: unless-stopped
    build: .
    ports:
      - $DOCKER_APP_PORT:$APP_PORT
    depends_on:
      - mongodb
    links:
      - mongodb
    environment:
      - MONGODB_HOST=mongodb
      